// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Genres = sequelize.define(
    'genres',
    {
      id: {
        type: DataTypes.UUID,
        primaryKey: true,
        defaultValue: Sequelize.literal('uuid_generate_v4()'),
      },
      name: {
        type: DataTypes.STRING,
      },
      createdAt: {
        type: DataTypes.DATE,
        defaultValue: Sequelize.literal('now()'),
      },
      updatedAt: {
        type: DataTypes.DATE,
        defaultValue: Sequelize.literal('now()'),
      },
    },
    {
      tableName: 'genres',
      underscored: true,
      schema: process.env.DATABASE_SCHEMA,
    },
  );

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Genres.associate = models => {
    Genres.belongsToMany(models.songs, {
      through: 'songsGenresGenres',
      foreignKey: 'genre_id',
      otherKey: 'song_id',
    });
    Genres.hasMany(models.songsGenresGenres, {
      foreignKey: {
        name: 'genreIdKey',
        field: 'genre_id',
      },
      as: 'songsGenresGenres2',
    });
  };

  return Genres;
};
